<?php
/**
 * Created by PhpStorm.
 * User: lapsh
 * Date: 23.03.2016
 * Time: 0:33
 */
include VIEWS . "_header.phtml";
?>

<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1>Index Page</h1>
    <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
    <p>
        <a class="btn btn-lg btn-primary" href="#" role="button">View navbar docs &raquo;</a>
    </p>
</div>


<?php
include VIEWS . "_footer.phtml";
