<?php

include VIEWS . "_header.phtml";
?>

<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1> <?=$data['title']?> </h1>
    <?=$data['test']?>
    <?php
//        echo '<pre>';
//        print_r($data);
//        echo "</pre>";
    ?>
    <table class="table table-striped table-hover ">
        <thead>
        <tr>
            <th>#</th>
            <th>Название</th>
            <th>Содержание</th>
            <th>Column heading</th>
        </tr>
        </thead>
        <tbody>
        <tr onclick="window.location.href = '/list/page/1'">
            <td>1</td>
            <td>Страница №1</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr  onclick="window.location.href = '/list/page/10'">
            <td>2</td>
            <td>Страница №10</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="info"  onclick="window.location.href = '/list/page/50/test_data'">
            <td>3</td>
            <td>Страница №50 c доп полем</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="success"  onclick="window.location.href = '/list/page/777/json'">
            <td>3</td>
            <td>Страница №777 в JSON</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        </tbody>
    </table>
</div>


<?php
include VIEWS . "_footer.phtml";
