<?php
/**
 * Created by PhpStorm.
 * User: lapsh
 * Date: 23.03.2016
 * Time: 0:33
 */
include VIEWS . "_header.phtml";
?>

<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1> <?=$data['title']?> </h1>
    <?=$data['test']?>
    <?php
//        echo '<pre>';
//        print_r($data);
//        echo "</pre>";
    ?>

</div>


<?php
include VIEWS . "_footer.phtml";
