<?php
/**
 * Created by PhpStorm.
 * User: lapsh
 * Date: 23.03.2016
 * Time: 0:33
 */
include ROOT . "/app/views/_header.phtml";
?>

<div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Error!</strong>
    <a href="javascript:void(0)" class="alert-link"> 404 not found!
</div>

<?php
include ROOT . "/app/views/_footer.phtml";